oslabs-beta/hypnos

client/App.jsx
client/Components/EndpointInput.jsx
client/Components/Menu.jsx
client/Components/QueryOutput.jsx
client/Components/RunQueryButton.jsx
client/Containers/QueriesContainer.jsx
client/Context.js
package-lock.json

I still have not rendered query input since Will and Sophie are working on that. Should eventually be rendered inside Query container.

React Boilerplate Setup - Hooks work in each component

---

client/App.jsx
client/Components/EndpointInput.jsx

Utilized Will and Sophie's method of useState to save data locally on the endpointInput component, then passed that to global context with dispatch. Able to access the result of the api endpoint field anywhere in the application

Working api endpoint field

---

client/App.jsx
client/Components/EndpointInput.jsx
client/Context.js
client/index.js

All stateful elements are now in context.js. App.jsx is clean and does not have to pass any props to the context provider. 9:00 7/24

Moved all state to context.js

---

client/App.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutput.jsx
client/Containers/QueriesContainer.jsx
client/Context.js
package-lock.json
package.json

--working graphql query and rendering of query output. needs dynamic input for query type
--added reducer to context for addQuery. was lost in merge from dev.
--added initial value for query in initial state

Will working qqo query

---

electron.js

- added edit menu with copy, paste, undo, redo functionality

edit menu added

---

client/App.jsx
client/Components/Menu.jsx
client/Context.js
package.json

Still needs styling, but reset button works in menu component. Basically resets the state to how it was before the user added any data. Will explain later on how it works.

merged sophie's commits and added reset state button in menu component

---

client/Components/QueryOutput.jsx
client/utils/jsonFormatter.js

Output now looks like code should with linebreaks and tabs
Co-authored-by: Will <wrobinson91@gmail.com>

first draft of output formatting

---

client/Components/EndpointInput.jsx

Co-authored-by: Will <wrobinson91@gmail.com>

implemented withApollo to change restLink

---

client/App.jsx
client/Components/EndpointInput.jsx
client/Components/QueryOutput.jsx
client/Containers/QueriesContainer.jsx
client/Context.js

Co-authored-by: Will <wrobinson91@gmail.com>

Query output is functional

---

client/App.jsx
client/Components/EndpointField.jsx
client/Components/Menu.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Components/RunQueryButton.jsx
client/Containers/QueriesContainer.jsx
client/Context.js

EndpointInput is now EndpointField
queryVar is now queryResultObject
greeting is gone
QueryOutput is now QueryOutputDisplay
QueryQueryObject is now OutputOfQuery
deleted some extraneous divs that were displaying context
Removed references to RunQueryButton but did not delete component. It is completely unused, but we can decide to delete later

Clarified naming conventions and cleaned up some divs

---

client/App.jsx
client/Components/EndpointField.jsx
client/Components/Menu.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Containers/QueriesContainer.jsx
client/StyleSheets/App.scss
client/StyleSheets/EndpointField.scss
client/StyleSheets/QueriesContainer.scss
index.html

adjusted grid to show query result inline with query input
grid/queries container now goes across entire app
basic html changes: 
- text area: font size, height
- .html file: changed root DIV to main
- changed app div to a section
- changed menu div to section
- changed endpoint field  div to article
- changed query input  div to article
- changed query output display  div to article
- changed queries container div to section

Will/html & css improvements

---

client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Containers/QueriesContainer.jsx
client/Context.js

Co-authored-by: Dillon Garrett <dillon.garrett.dev@gmail.com>
Co-authored-by: Sophie Nye <sophie.nye@gmail.com>

displays error message for incorrect endpoints

---

client/App.jsx
client/Components/EndpointField.jsx
client/Components/Menu.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Components/RunQueryButton.jsx
client/Constants/actionTypes.js
client/Containers/QueriesContainer.jsx
client/Context.js
client/StyleSheets/QueryOutputDisplay.scss
client/index.js
client/utils/jsonFormatter.js
electron.js
index.html

- added constants for action types. eslinted styling for all components
- fixed fetch CORS bug for normal fetch + apollo. used a proxy site. need to find better way (server?)
- added comments to endpoint field to figure out flickering issues
- added comments to menu
- added placeholder to queryinput, as well as move up 404 check in fetch promise chain.
- added to GQL types check in query output. removed loading H4.
- added charset tag to index.html.
-changed styling for queryoutput display.
-refined reducers in context.js

Will/CORS error fix, refined error handling

---

client/Components/EndpointField.jsx
client/Components/QueryInput.jsx
client/Context.js

moved new api endpoint state from context to query input + passed down to endpoint field. still need to clean context vars
STILL NEED RESET TO CLEAR INPUT FIELD

Will / fixed endpoint refresh bug

---

client/StyleSheets/_buttons.scss
client/StyleSheets/_endpointField.scss
client/StyleSheets/_queriesContainer.scss
client/StyleSheets/_queryInput.scss
client/StyleSheets/_queryOutputDisplay.scss

-adjusted endpoint field
-submit and reset buttons responsive
-spacing improved

styling updated

---

client/Components/QueryOutputDisplay.jsx
client/Containers/QueriesContainer.jsx
client/Context.js

--in query output display, if there is a result value in the reuslt object that looks like a URL (has 'http'), a UL and LI are built.
NOTE: this is not formatted in a nice-looking way.

Will/result that looks like URL given alert msg

---

client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx

TWO FETCHES
TWOOOOoOOOOOO FETCHEEESSSSS

Incorrect path throws error

---

client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Containers/QueriesContainer.jsx
client/Context.js
client/utils/fetchErrorCheck.js

--fixed error handling for QOD. allows nested REST queries, but now with parameterized nested path
--finally moved error handling into other file
--changed 404 error handling objs to gqlErrors. created constant files for dispatch objs and error strings (still empty)
--(COMMENTED OUT: have dispatch above error checking to see how nested rest calls look)

Will/fixed QOD error handling for URL-like results

---

client/Components/QueryOutputDisplay.jsx
client/utils/fetchErrorCheck.js

- changed some h4 tags to p tags
- added in line breaks
- fixed grammatical error

Small changes

---

client/App.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Constants/actionTypes.js
client/Containers/QueriesContainer.jsx
client/Context.js
client/utils/fetchErrorCheck.js
client/utils/jsonFormatter.js
dev/Code Snippets/DEV_QueryInput.jsx
electron.js

deleted unused vars, reducer, action types, unnecessary console logs. made pokeapi default. converted H4 tag to P tag for @rest error message

Will//cleaned up files, added comments, 

---

client/Context.js

fixed RESET_STATE reducer to retain queries history by returning initial state except current queriesHistory

Will/fixed RESET_STATE reducer to retain queries history

---

client/Components/HistoryDisplay.jsx
client/Components/HistoryListItem.jsx
client/StyleSheets/App.scss
client/StyleSheets/_historyDisplay.scss

Format of text needs to be decided upon - preliminary work completed

Styled history bar, buttons need to be styled

---

client/Components/HistoryDisplay.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Constants/actionTypes.js
client/Context.js
client/utils/handleQueryFetch.js

--fixed historical query not editable bug by resetting historicalText in context after it's assigned locally
--moved fetchChain in QI to new file. saves 100 lines of code in QI component
--added keys to auto-generated LIs to avoid React warnings
--reversed order of old queries so most recent appears at top

Will//fixed query history not editable bug; moved QI fetch to new file; cleaned up history display

---

client/Components/HistoryDisplay.jsx

you really just hate to see it

Will/fixed bug where LIs were constantly reversing after one was deleted

---

client/Components/HistoryDisplay.jsx
client/Components/HistoryListItem.jsx
client/StyleSheets/_buttons.scss
client/StyleSheets/_historyDisplay.scss

Added button render on hover for history bar. Additional styling needed, but it's a good start

Merged with Will's reverse changes

---

client/App.jsx
client/Components/APIKeyModal.jsx
client/Components/HistoryListItem.jsx
client/Constants/actionTypes.js
client/Containers/QueriesContainer.jsx
client/Context.js
client/StyleSheets/_queriesContainer.scss
package-lock.json
package.json

- created modal, 
- modified headers for custom fetch, 
- added apiKey and headersKey to context, 
-created APIKeyModal.jsx

authentication with API key

---

client/App.jsx
client/Components/APIKeyModal.jsx
client/Components/EndpointField.jsx
client/Components/HistoryDisplay.jsx
client/Components/MiniComponents/ErrorDisplay.jsx
client/Components/MiniComponents/HistoryListItem.jsx
client/Components/MiniComponents/NullResultCheck.jsx
client/Components/MiniComponents/URLResultCheck.jsx
client/Components/QueryInput.jsx
client/Components/QueryOutputDisplay.jsx
client/Constants/requestedContext.js
client/Containers/QueriesContainer.jsx
client/Containers/TabsManager.jsx
client/Context.js
client/utils/queryOutputDisplay/nullResultChecker.jsx

--created new components related to QOD that reduced file size by 75 lines.
--changed what's displayed inside history display
-- cleaned out old console logs and an unused file
--fixed some formatting

MORE MODULARITY. MORE.

---

client/Components/HistoryDisplay.jsx

history list item wasn't rendering right and broke the app!!
